# Generated by Django 2.1.7 on 2019-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sale', '0002_auto_20190216_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttabledata',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
