# Generated by Django 2.1.7 on 2019-02-18 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_sale', '0003_auto_20190216_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImportCientTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='discountpercentage',
            name='user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountpercentage',
            name='discount',
            field=models.TextField(default=10),
        ),
        migrations.AddField(
            model_name='clienttabledata',
            name='file_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_sale.FileImportCientTableData'),
        ),
    ]
