# Generated by Django 2.1.7 on 2019-02-18 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_sale', '0004_auto_20190218_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttabledata',
            name='status',
            field=models.IntegerField(default=False),
        ),
    ]
