# Generated by Django 2.1.7 on 2019-02-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sale', '0006_manageradminclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttabledata',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Prepay'), (1, 'Postpay')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clienttabledata',
            name='status',
            field=models.IntegerField(choices=[(0, 'NEW'), (1, 'WAIT'), (2, 'DONE'), (3, 'REJECT')], default=0, null=True),
        ),
    ]
