# Generated by Django 2.1.7 on 2019-02-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_sale', '0009_clientcreditrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttabledata',
            name='discount_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_admin', to='custom_sale.DiscountPercentage'),
        ),
        migrations.AddField(
            model_name='clienttabledata',
            name='discount_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_client', to='custom_sale.DiscountPercentage'),
        ),
    ]
